package describe

const (
	// --------------------------------------------------
	// Person/People Data Source
	// --------------------------------------------------
	PersonDataSourceDescription = "Returns a person in your xMatters instance using their unique identifier (UUID) or target name."
	PeopleDataSourceDescription = "Returns a list of people in xMatters that are visible to the authenticating user. You can request a list of users, or use the 'search' argument to return users that only match the specified criteria. When two or more search terms are present, the result includes people that match either search term."
	// Person Data Source Search Fields Schema
	PersonIDSearch = "Unique identifier (UUID) or target name of the xMatters user."
	// Person Data Source Schema
	PersonID              = "Unique identifier (UUID) of the xMatters user."
	PersonExternalKey     = "Unique identifier of the user in an external system."
	PersonExternallyOwned = "Whether the user is managed by an external system."
	PersonFirstName       = "First name of the user."
	PersonLanguage        = "Default language of the user."
	PersonLastName        = "Last name of the user."
	PersonLicenseType     = "License type of the user in xMatters. Available options are: FULL_USER, STAKEHOLDER_USER."
	PersonPhoneLogin      = "Access code used to retrieve phone messages from xMatters."
	PersonRoles           = "List of the user's assigned role names."
	PersonSite            = "Unique identifier (UUID) of the xMatters site the user is assigned to."
	PersonStatus          = "Status of the user. Available options are: ACTIVE,  INACTIVE."
	PersonSupervisors     = "List of unique identifiers (UUIDs) that represent the user's supervisors."
	PersonTargetName      = "User ID in xMatters consisting of a combination of letters and numbers up to 100 characters."
	PersonTimezone        = "Time zone where the user is located."
	PersonLastLogin       = "The date and time of the last time the person logged into xMatters."
	PersonWebLogin        = "Identifier used to log in to the xMatters user interface. This is often identical to the targetName value."
	PersonProperties      = "Custom fields and custom attributes for the user."
	PersonPropertyName    = "The name of the custom field."
	PersonPropertyValue   = "The value of the custom field."
	// People Data Source Schema
	PeopleSearch  = "Basic search parameters to find a list of xMatters users."
	PeopleFilters = "Search filters to improve the search results."
	PeopleOptions = "Sorting options for search results."
	PeopleList    = "List of available xMatters users."
	// People Data Source Search Fields Schema
	PeopleSearchTerms   = "List of search terms, separated by spaces. Used with the operand and fields parameters to expand or limit search results. When two or more search terms are present, the result includes services that match either search term."
	PeopleSearchOperand = "Operands expand or limit the search query parameter. OR is the default operand and returns services that have any of the search terms in the name or description. AND returns services that have all search terms in the name or description."
	PeopleSearchFields  = "Set the field to search when a search term is specified,. Available options are: FIRST_NAME, LAST_NAME, TARGET_NAME, WEB_LOGIN, EMAIL_ADDRESS, PHONE_NUMBER."
	// People Data Source Filters Fields Schema
	PeopleFiltersCreatedFrom       = "Timestamp in ISO format. Returns a list of users created after the provided value. Can be used on its own or in conjunction with the ‘createdBefore’ and ‘createdBefore’ parameters."
	PeopleFiltersCreatedTo         = "Timestamp in ISO format. Returns a list of users created before the provided value. Can be used on its own or in conjunction with the ‘createdAfter’ and ‘createdFrom’ parameters."
	PeopleFiltersCreatedBefore     = "Timestamp in ISO format. Returns a list of users created at or after the provided value. Can be used on its own or in conjunction with the ‘createdAfter’ and ‘createdFrom’ parameters."
	PeopleFiltersCreatedAfter      = "Timestamp in ISO format. Returns a list of users created up to and until the provided value. Can be used on its own or in conjunction with the ‘createdBefore’ and ‘createdTo’ parameters."
	PeopleFiltersDevices           = "If set to ‘true’, returns a list of users who have at least one email device associated with their account. If set to ‘false’, returns users with no email devices."
	PeopleFiltersDevicesEmail      = "If set to ‘true’, returns a list of users who have at least one failsafe device associated with their account. If set to ‘false’, returns users with no failsafe devices."
	PeopleFiltersDevicesFailsafe   = "If set to ‘true’, returns a list of users who have at least one device with the xMatters mobile app associated with their account. If set to ‘false’, returns users who have no devices with the mobile app."
	PeopleFiltersDevicesMobile     = "If set to ‘true’, returns a list of users who have at least one SMS device associated with their account. If set to ‘false’, returns users with no SMS devices."
	PeopleFiltersDevicesSMS        = "If set to ‘true’, returns a list of users who have at least one SMS device associated with their account. If set to ‘false’, returns users with no SMS devices."
	PeopleFiltersDevicesVoice      = "If set to ‘true’, returns a list of users who have at least one voice device associated with their account. If set to ‘false’, returns users with no voice devices."
	PeopleFiltersDevicesStatus     = "Status of the user’s devices in xMatters. Returns the devices that match the specified status. Available options are: ACTIVE, INACTIVE."
	PeopleFiltersDevicesTestStatus = "Whether xMatters has attempted to validate the user’s devices or not. Returns a list of users with devices that match the requested value. Values can be combined in a comma-separated list. Available options are: INVALID, TESTED, UNTESTED, UNTESTED_FAILSAFE, PENDING."
	PeopleFiltersEmailAddress      = "Email address of a user. Returns a list of users who have an email device with the provided value."
	PeopleFiltersFirstName         = "First name of a user. Returns a list of users with the provided value."
	PeopleFiltersGroups            = "Group target name (Base64-encoded) or unique ID. Returns a list of users who are direct members of the specified group. When multiple groups are specified, returns users who are members of at least one of the groups. Submit multiple values in a comma-separated list."
	PeopleFiltersGroupsExists      = "If set to ‘true’, returns a list of users who are members of at least one group. If set to ‘false’, returns users who are not members of any group."
	PeopleFiltersLastName          = "Last name of a user. Returns a list of users with the provided value."
	PeopleFiltersLicenseType       = "License type of a user. Returns a list of users with the provided value. Available options are: FULL_USER, STAKEHOLDER_USER."
	PeopleFiltersPhoneNumber       = "Phone number of a voice device. Returns a list of users who have a voice device with the specified phone number. Phone numbers must be in E.164 format. For example: 13065552241."
	PeopleFiltersRoles             = "Names of roles in xMatters. Returns a list of users who have the specified roles. When multiple roles are specified, the response returns users who have at least one of the roles. Values can be combined in a comma-separated list. The spelling of a role name must be an exact match to the name in xMatters, but is not case-sensitive."
	PeopleFiltersSite              = "Names or unique ID of sites in xMatters. Returns a list of users belonging to the specified site. Site names are case-sensitive."
	PeopleFiltersStatus            = "Status of a user. Returns users with the provided value. Available options are: ACTIVE, INACTIVE."
	PeopleFiltersSupervisors       = "Names or unique IDs of user supervisors. Returns a list of users assigned to the specified supervisors. Values can be combined in a comma-separated list. When multiple supervisors are specified, the response returns users who are assigned to at least one of the supervisors."
	PeopleFiltersSupervisorsExists = "If set to ‘true’, returns a list of users who are assigned to supervisors. If set to ‘false’, returns users who are not assigned to supervisors."
	PeopleFiltersTargetName        = "User ID in xMatters. A combination of letters and numbers is permitted with a maximum value of 100 characters. For example, a target name for Mary McBride could be 'mmcbride' or 'mcbride2418'."
	PeopleFiltersWebLogin          = "Identifier used to log in to the xMatters web user interface. If a value is not set in the request, the value of the target_name field is used. This field has a maximum of 100 characters."
	// People Data Source Options Fields Schema
	PeopleOptionsSortBy    = "Criteria for sorting the returned results. This parameter must be used together with the ‘sort_order’ query parameter. Available options are: FIRST_LAST_NAME, TARGET_NAME, STATUS, WEB_LOGIN, LAST_LOGIN, SITE, ROLES."
	PeopleOptionsSortOrder = "Order in which returned users are sorted. This parameter must be used together with the ‘sort_by’ query parameter. Available options are: ASCENDING, DESCENDING."
	// --------------------------------------------------
	// Person Resource
	// --------------------------------------------------
	PersonResourceDescription = "Create or update a user in xMatters.\n\nWhen adding new users, you must assign at least one role to a new user and you may optionally assign one or more supervisors. The supervisors must have permission to supervise users and the authenticating account must have permission to assign supervisors. If you do not assign a supervisor then the authenticating account becomes the user's supervisor."
	// Person Resource Schema
	PersonResourceID                 = "Unique identifier (UUID) of the xMatters user."
	PersonResourceTargetName         = "User ID in xMatters. A combination of letters and numbers is permitted with a maximum value of 100 characters. For example, a target name for Mary McBride  could be  'mmcbride' or 'mcbride2418'."
	PersonResourceFirstName          = "First name of the user."
	PersonResourceLastName           = "Last name of the user."
	PersonResourceRoles              = "Comma-separated list of xMatters role names to assign to the user."
	PersonResourceStatus             = "Status of the user in xMatters. Available options are: ACTIVE, INACTIVE. Default is ACTIVE."
	PersonResourceWebLogin           = "Identifier used to log in to the xMatters web user interface. If a value is not set in the request, the value of the target_name field is used. This field has  a maximum of 100 characters."
	PersonResourceSite               = "Unique ID of the site in your xMatters instance the user is assigned to. If a value is not provided, the site of the authenticating user is assigned."
	PersonResourceTimezone           = "Time zone where the user is located. The time zone must already be enabled in your xMatters instance."
	PersonResourceLanguage           = "Preferred language of the user. The language must already be enabled in your xMatters instance."
	PersonResourceSupervisors        = "Comma-separated list of unique identifiers (UUID) that represent the user's supervisors. Supervisors must have the role-based permissions required to supervise the user and the authenticating account must have permission to assign supervisors to the user. If empty or null, the user will have no supervisors. If the property is omitted from the request, the authenticating user who makes the request is set as the supervisor."
	PersonResourcePassword           = "Initial password assigned to the user."
	PersonResourceForcePasswordReset = "If set to 'true' the user must reset their password when they next log in. Available values are: true, false."
	PersonResourcePhoneLogin         = "An access code for the user to identify themselves when they phone into xMatters to retrieve messages. The phone login has a maximum length of 30 characters and must only contain digits. You can also set an optional phone PIN for the user."
	PersonResourcePhonePin           = "Used with phone_login, the optional PIN a user enters to identify themselves when they phone into xMatters to retrieve messages. The PIN has a maximum length of 30 characters and must only contain digits. Once submitted in the request, the phone PIN is not returned or displayed in the response object."
	PersonResourceLicenseType        = "xMatters user license type. Available options are: FULL_USER, STAKEHOLDER_USER. Default is FULL_USER."
	PersonResourceExternalKey        = "Unique identifier of a resource in an external system."
	PersonResourceExternallyOwned    = "Whether the object is managed by an external system. Available options are: true, false. Default value is false."
	PersonResourceProperties         = "Values of custom fields and custom attributes for this person."
	PersonResourceTextProperty       = "Property value that accepts a string. Supports Text, Password, and List property types."
	PersonResourceIntProperty        = "Property value that accepts a numeric value.  Supports Number property type."
	PersonResourceBoolProperty       = "Property value that accepts a boolean value. Supports Check Box property type."
	PersonResourceMultiListProperty  = "Property value that accepts a list of string values. Supports Multi-Select property type."
	PersonResourcePasswordProperty   = "Property value that accepts a password. Supports Password property type."
)
